# Generated by Django 5.1.3 on 2024-11-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], max_length=2)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
